---
name: silverstripe-shopify-config
---
Dynamic\Shopify\Page\ShopifyProduct:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CatalogPageExtension
  parent_classes:
    - Dynamic\Shopify\Page\ShopifyCollection
  sort_column: false
  automatic_live_sort: false

SilverStripe\Security\Member:
  extensions:
    - Dynamic\Shopify\Extension\ShopifyMember

PageController:
  extensions:
    - Dynamic\Shopify\Extension\ShopifyExtension

Dynamic\Shopify\Controller\Webhook\WebhookController:
  type_routing:
    products: Dynamic\Shopify\Controller\Webhook\ProductWebhookController
    collections: Dynamic\Shopify\Controller\Webhook\CollectionWebhookController

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\LoginHandler:
    class: Dynamic\Shopify\Extension\ShopifyLoginHandler
