---
name: silverstripe-shopify-config
---
Dynamic\Shopify\Page\ShopifyProduct:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CatalogPageExtension
  parent_classes:
    - Dynamic\Shopify\Page\ShopifyCollection
  active_schema:
    - Dynamic\Shopify\SEO\ProductSchemaBuilder
  sort_column: false
  automatic_live_sort: false

SilverStripe\Security\Member:
  extensions:
    - Dynamic\Shopify\Extension\ShopifyMember

PageController:
  extensions:
    - Dynamic\Shopify\Extension\ShopifyExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\LoginHandler:
    class: Dynamic\Shopify\Extension\ShopifyLoginHandler
