---
name: silverstripe-shopify-config
---
Dynamic\Shopify\Page\ShopifyProduct:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CatalogPageExtension
  parent_classes:
    - Dynamic\Shopify\Page\ShopifyCollection
  sort_column: false

SilverStripe\Security\Member:
  extensions:
    - Dynamic\Shopify\Extension\ShopifyMember
