---
name: silverstripe-shopify-config
---
Dynamic\Shopify\Page\Product:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CatalogPageExtension
  parent_classes:
    - Dynamic\Shopify\Page\ProductCollection

SilverStripe\Security\Member:
  extensions:
    - Dynamic\Shopify\Extension\ShopifyMember
