---
name: silverstripe-shopify-routes
after:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    'multipass': 'Dynamic\Shopify\Controller\ShopifyMultipassController'
    'webhooks/shopify//$Action': 'Dynamic\Shopify\Controller\WebhookController'
