# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

name: "CI"

jobs:
  tests:
    name: "Tests"

    runs-on: "ubuntu-latest"

    env:
      php_extensions: ctype, dom, fileinfo, hash, intl, mbstring, session, simplexml, tokenizer, xml, pdo, mysqli, gd, zip

    services:
      mysql:
        image: "mysql:5.7"
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: test_db
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.php_extensions }}"
          coverage: "xdebug"

      - name: "Start mysql service"
        run: "sudo /etc/init.d/mysql start"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "~/.composer/cache"
          key: "php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install dependencies with composer"
        run: "composer install --no-ansi --no-interaction --no-progress"

      - name: "Run tests with phpunit/phpunit"
        env:
          SS_DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: "vendor/bin/phpunit --coverage-html=build/logs/coverage/html --coverage-xml=build/logs/coverage"

      - name: "Archive code coverage results"
        uses: "actions/upload-artifact@v2"
        with:
          name: "coverage"
          path: "build/logs/coverage/html"

      - name: "Run tests with squizlabs/php_codesniffer"
        run: "vendor/bin/phpcs -s --report=summary --standard=phpcs.xml.dist --extensions=php,inc --ignore=autoload.php --ignore=vendor/ src/ tests/"

      - name: "Run tests with phpmd/phpmd"
        run: "vendor/bin/phpmd src html codesize,unusedcode,naming --reportfile build/logs/phpmd.html --exclude vendor/ --exclude autoload.php || exit 0"

      - name: "Archive phpmd results"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpmd"
          path: "build/logs/phpmd.html"
